### ISSUE TITLE
"fixed" notification not working

### ISSUE THREAD

**Issue by vdebergue** [mockersf/concourse-slack-notifier#23]
The notifier is not sending "fixed" information to slack anymore. 
It's hard to know the cause as the notifier is not providing enough information or logs to debug the issue.

The only thing present is the resource status: "Did not send Fixed notification to #xxx"

**Comment by mockersf** [comment]
user specified did not have access to team of pipeline

**Comment by acarsercan** [comment]
Unfortunately I'm seen this problem

```    
    on_failure:
      params:
        alert_type: failed
        channel: '#XXX'
        mode: concise
      put: Slack
    on_success:
      params:
        alert_type: fixed
        channel: '#XXX'
        mode: concise
      put: Slack
```

Yet `fixed` alert is never sent with concourse UI error 

```

status | Did not send Fixed notification to #dynamo
-- | --


```

Any ideas? I'm setting username & password in the resource type
